# Generated by Django 4.1.2 on 2023-08-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_remove_hubdoggymodel_photo_photodoggymodel_doggy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodoggymodel',
            name='doggy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='hub.hubdoggymodel'),
        ),
    ]
