# Generated by Django 4.1.2 on 2023-08-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_profile_delete_usersmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
