# Generated by Django 4.1.2 on 2023-08-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_alter_photodoggymodel_doggy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodoggymodel',
            name='doggy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.hubdoggymodel'),
        ),
    ]
