# Generated by Django 4.1.2 on 2023-08-16 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0010_hubdoggymodel_seller_alter_photodoggymodel_doggy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubdoggymodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
