# Generated by Django 4.1.2 on 2023-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_alter_hubdoggymodel_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubdoggymodel',
            name='species',
            field=models.CharField(default='', max_length=255),
        ),
    ]
